### ISSUE TITLE
config-file

### ISSUE THREAD

**Issue by marco-taylor** [fbeek/maxcul2mqtt#1]
Hello Florian,

can you please describe how to use it, please.
How I can run it and add an device?

Regards
Marco

**Comment by marco-taylor** [comment]
Hello,

I have it running, but I get the following error message "Requested device not in database."
I used the cul in fhem before and the device was already paired, so I simply added the device to the config-file.

Regards
Marco

**Comment by fbeek** [comment]
Hello Marco,

The version here on GitHub is an older one. I have a newer version that includes some fixes, example configs, example database files, and some Home Assistant example configs.

However, it needs some polishing.

If you give me one or two days, I will clean it up and publish it here so that you have some examples.

Please be advised that this solution is not perfect. It worked for me for some years but has some quirks.

I cannot provide much support here, mainly because of timing issues, but also because I have not used the MAX! CUL for my heating since this year and have no devices for testing.

Regards,
Florian

**Comment by marco-taylor** [comment]
Hello Florian,

that would be great. I have now successfully paired a device, but I cannot transfer it to home assistant via Mosquitto.
If you have configs for homeassistant, that would be great!

Regards
Marco

**Comment by marco-taylor** [comment]
Update:
This is what my maxcul2mqtt currently shows, which looks good:
```
 [34mMaxcul2MQTT:debug [39m 2024-05-22T05:34:51+02:00: Send online message for device: 17f74E 
2024-05-22 05:34:51.493248+02:00 [32mMaxcul2MQTT:info  [39m 2024-05-22T05:34:51+02:00: MQTT publish: topic 'maxcul2mqtt/17f74E/availability', payload 'online' 
2024-05-22 05:34:51.493320+02:00 [32mMaxcul2MQTT:info  [39m 2024-05-22T05:34:51+02:00: MQTT publish: topic 'maxcul2mqtt/17f74E/state', payload '{"mode":"1","desiredTemperature":19,"valvePosition":0,"measuredTemperature":21.6,"dstSetting":1,"langateway":1,"panel":0,"rferror":1,"batterylow":0,"untilString":"","lastUpdate":"Wed May 22 2024 01:32:44 GMT+0200 (Central European Summer Time)","haMode":"heat"}'
```
And this is what my mosquitto currently shows:
`2024-05-22 05:24:51.474308+02:001716348291: New client connected from 172.16.3.233:42662 as maxcul2mqtt (p2, c1, k120, u'mqtt_user').`

But homeassistant cannot find a new device. Of course, this could also be due to the homeassistant-mqtt settings (search term: homeassistant).

Regards,
Marco

**Comment by fbeek** [comment]
Hello Marco,

first thank you very much for your donation, such a form of kindness helps the open source community allot !

I have cleaned up the code and added some more example for the configs and database.

I have also added an examples folder, here you find some of my production examples that i have used. One file contains configs for window contacts (binary_sensors) and heating valves (climate). You can add these to your homeassistant config under the corresponding config sections.

 Be advised that you need to change the IDs inf the configs according your device ids.

Also there is the correct mqtt path configuration in the HA config examples.

With this setup you can change the values of the Valves an get the corresponding values if you change it at the device itself. The valves need to be in manual mode. You cannot set schedules with my software, but you can easily do that with homeassistant automations.

I have never bound the devices together, i did everything in HA (when Window open -> disable valve etc.), but theoretically the software supports it. 

I hope this helps you to get it running.

Regards
Florian

**Comment by marco-taylor** [comment]
Hello Florian,

thanks for sharing.
But I have a problem to integration it into Home Assistant.

In mosquitto is everything fine:
```
MQTT-Explorer:
- maxcul2mqtt
   - bridge
     state = offline
   - 17f745
     availability = online
     state = {"mode":"1","desiredTemperature":20,"valvePosition":15,"measuredTemperature":21.1,"dstSetting":1,"langateway":1,"panel":0,"rferror":1,"batterylow":0,"untilString":"","lastUpdate":"Thu May 23 2024 04:44:47 GMT+0200 (Central European Summer Time)","haMode":"heat"}
```
I have add the climate-exsample to my configuration.yaml like the [MQTT-Sensor](https://www.home-assistant.io/integrations/sensor.mqtt/):

```
mqtt:
  sensor:
    - name: "EG_KU_HZ"
      unique_id: "eg_ku_hz"
      modes:
        - "off"
        - "heat"
      current_temperature_topic: "maxcul2mqtt/17f745/state"
      current_temperature_template: "{{ value_json.measuredTemperature }}"
      temperature_state_topic: "maxcul2mqtt/17f745/state"
      temperature_state_template: "{{ value_json.desiredTemperature }}"
      temperature_command_topic: "maxcul2mqtt/bridge/cmd/17f745/setTemp"
      #action_topic: "maxcul2mqtt/17f745/state"
      #action_template: "{{value_json.haMode}}"
      availability_topic: "maxcul2mqtt/17f745/availability"
      temp_step: 0.5
      max_temp: 30.6
      min_temp: 4.5
      precision: 0.1
      mode_command_topic: "maxcul2mqtt/bridge/cmd/17f745/setMode"
      mode_state_topic: "maxcul2mqtt/17f745/state"
      mode_state_template: "{{ value_json.haMode }}"
```

But I get the following error:

[https://www.home-assistant.io/integrations/sensor.mqtt/](MQTT-Sensor)


![2024-05-23 05_52_17-Einstellungen – Home Assistant und 10 weitere Seiten - Geschäftlich – Microsoft​](https://github.com/fbeek/maxcul2mqtt/assets/166688274/4f10f1ce-c112-4e49-8375-3cb79efa3a31)

Maybe you can see the error.

Regards,
Marco


UPDATE:
```
mqtt:
  - climate:
    - name: "EG_KU_HZ"
      unique_id: "eg_ku_hz"
      modes:
        - "off"
        - "heat"
```

Change sensor: to **- climate:** fix the problem.
