### ISSUE TITLE
value is not adopted

### ISSUE THREAD

**Issue by marco-taylor** [fbeek/maxcul2mqtt#2]
Hello Florian,

if I change the value of the thermostat in Homeassistant, it arrives in mosquitto (setTemp = 12.0), but is not adopted by the thermostat.
Any idea what this could be?

My MAXCul runs version 1.26.04 .

Regards,
Marco

**Comment by fbeek** [comment]
Hello Marco,

did you see something in the log from maxcul2mqtt ? There you should the incoming message and what my tool does with it if you define the debug level DEBUG in the config.

Please check the Device ID, they need to match everywhere.

It can be that you have reached the MAX! send limit that is implemented in the CUL firmware.

If you see something like a LOVF Message, this means it has reaches it transmit limit and has not send any package.
Please look in the other closed Issues or the readme for the 868MHz Band 1% transmit limit in the EU.

Here you can find detailed infos according the LOVF topic : https://wiki.fhem.de/wiki/LOVF

If you need more help according this please send me some logs here.

**Comment by marco-taylor** [comment]
Hello Florian,

MQTT-Explorer shows the incoming message from Homeassistant:
![2024-05-23 13_47_39-MQTT Explorer – Mozilla Firefox](https://github.com/fbeek/maxcul2mqtt/assets/166688274/d39db088-74e0-416f-b0c7-c521245f51ae)

also the log from maxcul2mqtt shows it:
![2024-05-23 13_49_14-TrueNAS - 192 168 178 100 – Mozilla Firefox](https://github.com/fbeek/maxcul2mqtt/assets/166688274/2a801a79-c7de-43ca-8904-239a80ad96ff)

but the value is also not changed in the database.db.

I have set the correct path in the configuration.yaml , can that be a problem?

configuration.yaml:
```
default:
  logger:
    log_rotation: true
    log_output: "console" ## console or file
    log_directory: ""
    log_file: "log.txt"
    log_level: "debug"
  mqtt:
    base_topic: "maxcul2mqtt"
    server: "mqtt://mosquitto.ix-mosquitto.svc.cluster.local"
    keepalive: 120
    #ca: "",
    #key: "",
    #cert: "",
    user: "mqtt_user"
    password: "xyzxyz"
    client_id: "maxcul2mqtt"
  maxcul:
    homeBaseAdress: "xxxxxx"
    baudrate: 9600
    port: "/dev/ttyACM0"
    pairModeEnabled: false
  advanced:
    cache_state_persistent: true
  database:
    db_path: "/app/storage"
    db_file: "database.db"
  devices:
    "128e2d":
      label: "EG_WE_W_HZ"
      deviceId: "128e2d"
      deviceType: "Thermostat"
      groupId: '00'
      ecoTemp: 17
      comfyTemp: 20
      minimumTemperature: 4.5
      maximumTemperature: 30.5
      measurementOffset: 0
      windowOpenTime: 60
      windowOpenTemperature: 4.5
      guiShowValvePosition: true
      pairIds: []
```

By writing this I have found the error ;-)

Change  the  _homeBaseAdress: "xxxxxx"_ to  **homeBaseAdress: "123456"** fix my problem.
I forgot to change it in the new config...... damm!

Regards,
Marco
